"""뉴질랜드 IP 주소 목록 만들기 → src/geo/nz-ip.json (서버가 접속 IP로 통화를 고를 때 씀)
실행: python3 scripts/nz-ip.py   (가끔 다시 실행해 최신으로 — 주소 할당은 조금씩 바뀜)

자료: 5개 지역 인터넷 등록기관(RIR)이 매일 공개하는 주소 할당 통계(delegated stats) 중 국가 코드가 NZ인 것.
      APNIC(아시아·태평양)이 대부분이고, 다른 지역 기관에서 뉴질랜드로 할당된 것도 함께 넣는다.
- IPv4: [시작, 끝] 정수 구간(이어지는 구간은 합침)
- IPv6: [앞부분 32자리 16진수, 접두사 길이]
"""
import ipaddress, json, sys, urllib.request
from datetime import date
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / 'src/geo/nz-ip.json'
SOURCES = {
    'apnic': 'https://ftp.apnic.net/stats/apnic/delegated-apnic-latest',
    'arin': 'https://ftp.arin.net/pub/stats/arin/delegated-arin-extended-latest',
    'ripencc': 'https://ftp.ripe.net/pub/stats/ripencc/delegated-ripencc-latest',
    'lacnic': 'https://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-latest',
    'afrinic': 'https://ftp.afrinic.net/pub/stats/afrinic/delegated-afrinic-latest',
}


def main():
    v4, v6, dates = [], [], {}
    for name, url in SOURCES.items():
        print('받기', url)
        with urllib.request.urlopen(url, timeout=180) as r:
            text = r.read().decode('utf-8', 'replace')
        n = 0
        for line in text.splitlines():
            if line.startswith('#'):
                continue
            f = line.split('|')
            if len(f) >= 4 and f[0][:1].isdigit():  # 머리줄: 버전|기관|일련번호|건수|시작일|종료일|…
                dates[name] = f[5] if len(f) > 5 else ''
                continue
            if len(f) < 7 or f[1] != 'NZ' or f[6] not in ('allocated', 'assigned'):
                continue
            if f[2] == 'ipv4':
                start = int(ipaddress.IPv4Address(f[3]))
                v4.append([start, start + int(f[4]) - 1]); n += 1
            elif f[2] == 'ipv6':
                net = ipaddress.IPv6Network(f'{f[3]}/{f[4]}', strict=False)
                v6.append([f'{int(net.network_address):032x}', net.prefixlen]); n += 1
        print(f'  NZ {n}건')

    v4.sort()
    merged = []
    for a, b in v4:
        if merged and a <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], b)
        else:
            merged.append([a, b])
    v6 = sorted({tuple(x) for x in v6})
    if len(merged) < 50 or len(v6) < 50:
        sys.exit(f'목록이 너무 적습니다(IPv4 {len(merged)}, IPv6 {len(v6)}) — 자료를 확인하세요')
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps({
        'about': 'New Zealand (NZ) IP ranges from RIR delegated statistics (APNIC, ARIN, RIPE NCC, LACNIC, AFRINIC). Generated by scripts/nz-ip.py',
        'generated': date.today().isoformat(),
        'sources': dates,
        'v4': merged,
        'v6': [list(x) for x in v6],
    }, separators=(',', ':')) + '\n')
    total = sum(b - a + 1 for a, b in merged)
    print(f'완료: {OUT.relative_to(OUT.parents[2])} — IPv4 {len(merged)}구간({total:,}개 주소), IPv6 {len(v6)}개, {OUT.stat().st_size / 1024:.0f} KB')


if __name__ == '__main__':
    main()
